#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# SPDX-License-Identifier: CC0-1.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

if ! command -v git > '/dev/null'; then
	printf '%s: git: program missing\n' "$argv0" >&2
	exit 27
fi

if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %d\n' "$argv0" $# >&2
	exit 4
fi

case "$(git rev-parse --is-bare-repository)" in
	('true') exit ;;
	('false') ;;
	(*)
		# shellcheck disable=SC2016
		printf '%s: unexpected output of `git rev-parse --is-bare-repository`\n' "$argv0" >&2

		exit 104
		;;
esac

tmp="$(git diff --staged --name-only -- '*.ts' '*.mts' '*.js' '*.mjs' '*.json' | wc -c)"
if [ "$tmp" = '0' ]; then
	printf 'No TypeScript, JavaScript nor JSON files staged. Skipping commit hook.\n' >&2
	exit
fi
unset -v tmp

if ! command -v npm > '/dev/null'; then
	printf '%s: npm: program missing\n' "$argv0" >&2
	exit 27
fi

npm run-script git-pre-commit
